discuss/lib/discuss_web/router.ex
defmodule DiscussWeb.Router do
  use DiscussWeb, :router

  pipeline :browser do
    plug Ueberauth
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug DiscussWeb.Plugs.SetUser # module plug
  end

  # pipeline :authenticate_user do
  # end

  pipeline :api do
    plug :accepts, ["json"]
    # plug :cors
  end

  scope "/", DiscussWeb do
    pipe_through :browser # Use the default browser stack

    get "/", TopicController, :index
    resources "/topics", TopicController
  end


  scope "/auth", DiscussWeb do
    pipe_through :browser

    get "/logout", AuthController, :logout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", DiscussWeb do
  #   pipe_through :api
  # end
end

discuss/lib/discuss/application.ex
defmodule Discuss.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Discuss.Repo, []),
      # Start the endpoint when the application starts
      supervisor(DiscussWeb.Endpoint, []),
      # Start your own worker by calling: Discuss.Worker.start_link(arg1, arg2, arg3)
      # worker(Discuss.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Discuss.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    DiscussWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

discuss/lib/discuss/comment.ex
defmodule Discuss.Comment do
  use Discuss, :model

  schema "comments" do
    field :content, :string

    belongs_to(:user, Discuss.User)
    belongs_to(:topic, Discuss.Topic)

    timestamps()
  end

  def changeset(struct, attrs \\ %{}) do
    struct
    |> cast(attrs, [:content])
    |> validate_required([:content])
  end

end

discuss/lib/discuss/repo.ex
defmodule Discuss.Repo do
  use Ecto.Repo, otp_app: :discuss

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

discuss/lib/discuss/topic.ex
defmodule Discuss.Topic do
  use Discuss, :model

  schema "topics" do
    field :title, :string

    belongs_to(:user, Discuss.User)
    has_many(:comments, Discuss.Comment)

    timestamps()
  end

  @doc false
  def changeset(struct, attrs \\ %{}) do
    struct
    |> cast(attrs, [:title])
    |> validate_required([:title])
    |> validate_length(:title, min: 2)
  end
end

discuss/lib/discuss/user.ex
defmodule Discuss.User do
  use Discuss, :model

  schema "users" do
    field :email, :string
    field :provider, :string
    field :token, :string
    field :user_name, :string
    field :full_name, :string
    field :image_url, :string

    has_many(:topics, Discuss.Topic)
    has_many(:comments, Discuss.Comment)

    timestamps()
  end

  def changeset(struct, attrs \\ %{}) do
    struct
    |> cast(attrs, [:email, :provider, :token, :user_name, :full_name, :image_url])
    |> validate_required([:email, :provider, :token])
  end
end

discuss/lib/discuss_web/controllers/auth_controller.ex
defmodule DiscussWeb.AuthController do
  use DiscussWeb, :controller

  alias Discuss.{User, Repo}

  plug Ueberauth


  defp insert_or_update_user(changeset) do
    case Repo.get_by(User, email: changeset.changes.email) do
      user ->
        {:ok, user}
      nil ->
        Repo.insert(changeset)
    end
  end


  defp login(conn, changeset) do
    case insert_or_update_user(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Welcome #{user.email}")
        |> put_session(:user_id, user.id)
        |> redirect(to: topic_path(conn, :index))
      {:error, _reason} ->
        conn
        |> put_flash(:error, "Error logging in")
        |> redirect(to: topic_path(conn, :index))
    end
  end


  def logout(conn, _params) do
    conn
    |> configure_session(drop: true)
    |> put_flash(:info, "Good Bye!")
    |> redirect(to: topic_path(conn, :index))
  end


  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, _params) do
    user_params = %{
      token: auth.credentials.token,
      email: auth.info.email,
      provider: to_string(auth.provider),
      user_name: auth.info.nickname,
      full_name: auth.info.name,
      image_url: auth.info.image
    }

    changeset = User.changeset(%User{}, user_params)

    login(conn, changeset)
  end
end

discuss/lib/discuss_web/controllers/page_controller.ex
defmodule DiscussWeb.PageController do
  use DiscussWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end

  def about(conn, _params) do
    render conn, "about.html"
  end
end

discuss/lib/discuss_web/controllers/topic_controller.ex
defmodule DiscussWeb.TopicController do
  use DiscussWeb, :controller

  alias Discuss.{Topic, Repo}

  plug DiscussWeb.Plugs.RequireAuth when action in [
    :new, :create, :update, :edit, :delete
  ]

  plug :check_topic_owner when action in [
    :edit, :update, :delete
  ]

  def index(conn, _params) do
    topics = Repo.all(Topic)
    render conn, "index.html", topics: topics
  end


  def show(conn, %{"id" => topic_id}) do
    topic = Repo.get!(Topic, topic_id)
    render conn, "show.html", topic: topic
  end


  def new(conn, _params) do
    changeset = Topic.changeset(%Topic{}, %{})

    render conn, "new.html", [changeset: changeset]
  end


  def create(conn, %{"topic" => topic}) do

    changeset = conn.assigns[:user]
      |> Ecto.build_assoc(:topics)
      |> Topic.changeset(topic)

    case Repo.insert(changeset) do
      {:ok, _topic} ->
        conn
        |> put_flash(:info, "Topic created successfully.")
        |> redirect(to: topic_path(conn, :index))
      {:error, changeset} ->
        conn
        |> put_flash(:error, "Error creating Topic")
        |> render("new.html", changeset: changeset)
    end
  end


  def edit(conn, %{"id" => topic_id}) do
    topic = Repo.get(Topic, topic_id)
    changeset = Topic.changeset(topic)

    render conn, "edit.html", changeset: changeset, topic: topic
  end


  def update(conn, %{"id" => topic_id, "topic" => topic}) do
    old_topic = Repo.get(Topic, topic_id)
    changeset = Topic.changeset(old_topic, topic)

    case Repo.update(changeset) do
      {:ok, topic} ->
        conn
        |> put_flash(:info, "Topic #{topic.id} updated successfully.")
        |> redirect(to: topic_path(conn, :index))
      {:error, changeset} ->
        conn
        |> put_flash(:error, "Error updating Topic")
        |> render("edit.html", changeset: changeset, topic: old_topic)
    end
  end


  def delete(conn, %{"id" => topic_id}) do
    Repo.get!(Topic, topic_id) |> Repo.delete!

    conn
    |> put_flash(:info, "Topic deleted")
    |> redirect(to: topic_path(conn, :index))
  end

  def has_user?(conn) do
    Map.has_key?(conn.assigns, :user)
  end

  defp check_topic_owner(conn, _params) do
    %{params: %{"id" => topic_id }} = conn

    if has_user?(conn) && Repo.get(Topic, topic_id).user_id == conn.assigns.user.id do
      conn
    else
      conn
      |> put_flash(:error, "You cannot edit this topic")
      |> redirect(to: topic_path(conn, :index))
      |> halt()
    end
  end
end

discuss/lib/discuss_web/views/error_view.ex
defmodule DiscussWeb.ErrorView do
  use DiscussWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

discuss/lib/discuss_web/views/layout_view.ex
defmodule DiscussWeb.LayoutView do
  use DiscussWeb, :view
end

discuss/lib/discuss_web/views/page_view.ex
defmodule DiscussWeb.PageView do
  use DiscussWeb, :view
end

discuss/lib/discuss_web/views/topic_view.ex
defmodule DiscussWeb.TopicView do
  use DiscussWeb, :view
end

discuss/lib/discuss_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Discuss!</title>

     <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav class="light-blue">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">
          Discussions
        </a>
        <ul class="right">
          <li>
            <%# <%= if @conn.assigns[:user] %>
            <%= if assigns.user do %>
              <%= assigns.user.full_name %>
              <%= link "Logout", to: auth_path(@conn, :logout), class: "waves-effect waves-light btn grey darken-1" %>
            <% else %>
              <%= link "Login with GitHub", to: auth_path(@conn, :request, "github"), class: "waves-effect waves-light btn grey darken-1" %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div>
     <!-- /container -->

    <script>
      var _msgs = {
        info: "<%= get_flash(@conn, :info) %>",
        error: "<%= get_flash(@conn, :error) %>"
      };
      if (M && M.toast) {
        _msgs.info && M.toast({
          html: _msgs.info,
          classes: 'toast-info'
        });
        _msgs.error && M.toast({
          html: _msgs.error,
          classes: 'toast-error'
        });
      }
    </script>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

discuss/lib/discuss_web/templates/topic/edit.html.eex
<%= form_for @changeset, topic_path(@conn, :update, @topic), fn f -> %>
  <div class="form-group">
    <%= text_input f, :title, [placeholder: "Title", class: "form-control", id: "title"] %>
    <%= error_tag f, :title %>
  </div>

  <button class="btn btn-primary waves-effect waves-light" type="submit" name="action">
    <i class="material-icons right">send</i>Update Topic
  </button>
<% end %>

discuss/lib/discuss_web/templates/topic/index.html.eex
<h5>All Topics</h5>

<ul class="collection">
  <%= for topic <- @topics do %>
    <li class="collection-item">
      <%= link topic.title, to: topic_path(@conn, :show, topic) %>

      <%= if @conn.assigns.user && @conn.assigns.user.id == topic.user_id do %>
      <div class="right">
        <%= link to: topic_path(@conn, :edit, topic) do %>edit<% end %>
        &nbsp;
        <%= link to: topic_path(@conn, :delete, topic), method: :delete do %>delete<% end %>
      <div>
      <% end %>
    </li>
  <% end %>
</ul>

<% if assigns[:user] do %>
  <div class="fixed-action-btn">
    <%= link to: topic_path(@conn, :new), class: "btn-floating btn-large waves-effect waves-light red" do %>
      <i class="material-icons">add</i>
    <% end %>
  </div>
<% end %>

discuss/lib/discuss_web/templates/topic/new.html.eex
<%= form_for @changeset, topic_path(@conn, :create), fn f -> %>
  <div class="form-group">
    <%= text_input f, :title, [placeholder: "Title", class: "form-control", id: "title"] %>
    <%= error_tag f, :title %>
  </div>

  <button class="btn btn-primary waves-effect waves-light" type="submit" name="action">
    <i class="material-icons right">send</i>Save Topic
  </button>
<% end %>

discuss/lib/discuss_web/templates/topic/show.html.eex
<h5><%= @topic.title %></h5>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    window.createSocket({ topicId: "<%= @topic.id %>" });
  });
</script>